version: '2'
services:

  springbootapp:
    build:
      context: ./app/backend 
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    environment:
      - backend.neo4j.uri=bolt://10.0.21.18:7687
      - backend.neo4j.username=neo4j
      - backend.neo4j.password=password
      - backend.public_domain=http://10.0.21.18:8080/
    depends_on:
      - neo4j 

  neo4j:
    image: neo4j:5.16.0
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/password
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4j_db_data:/data

volumes:
  neo4j_db_data: